import contextlib
import copy
from datetime import datetime, timezone
import io
import json
import os
import tempfile
import unittest
from unittest import mock
from urllib.error import HTTPError

import recent_stats
from recent_stats import (GitHubClient, GitHubError, classify, commit_changes,
                          display_name, list_commits, repo_changes, retry_delay,
                          transform)


NOW = datetime(2026, 10, 8, tzinfo=timezone.utc)
SINCE = datetime(2025, 10, 8, tzinfo=timezone.utc)
USER = "TomNewChao"


def commit(sha, author=USER, parents=1):
    return {"sha": sha, "parents": [{}] * parents,
            "author": {"login": author} if author else None}


def changed(name, additions, deletions=0, status="modified", patch=None):
    return {"filename": name, "additions": additions, "deletions": deletions,
            "status": status, "patch": patch}


class FakeClient:
    """Stands in for GitHubClient: commit lists per repo, file pages per commit."""

    def __init__(self, commits=None, details=None, fail=()):
        self.commits = commits or {}
        self.details = details or {}
        self.fail = set(fail)
        self.repos_asked = []

    def pages(self, path, params=None):
        repo, _, tail = path[len("/repos/"):].partition("/commits")
        if repo in self.fail:
            raise GitHubError("HTTP 404")
        if params is not None:
            self.params = params
            self.repos_asked.append(repo)
            yield self.commits.get(repo, [])
        else:
            for files in self.details[(repo, tail.lstrip("/"))]:
                yield {"files": files}


class FakeResponse(io.BytesIO):
    def __init__(self, payload, link=""):
        super().__init__(json.dumps(payload).encode())
        self.headers = {"Link": link} if link else {}


def http_error(code, headers=None, body=b"{}"):
    return HTTPError("https://api.github.com/x", code, "error", headers or {},
                     io.BytesIO(body))


class ClassifyTests(unittest.TestCase):
    def test_counts_source_files(self):
        for name, language in [("src/main.go", "Go"), ("web/App.tsx", "TypeScript"),
                               ("Dockerfile", "Dockerfile"),
                               ("docker/Dockerfile.prod", "Dockerfile"),
                               ("Makefile", "Makefile"), ("a/B.CS", "C#"),
                               ("net8.0/app.cs", "C#")]:
            with self.subTest(name):
                self.assertEqual(classify(name), (language, ""))

    def test_ignores_documentation_data_and_unknown_files(self):
        self.assertEqual(classify("README.md"), (None, "non-code"))
        self.assertEqual(classify("plc4net/plc4net.sln"), (None, "non-code"))
        self.assertEqual(classify("a/package-lock.json"), (None, "non-code"))
        self.assertEqual(classify("src/unknown.xyz"), (None, "unrecognised:.xyz"))
        # Extensionless names are never echoed: they could be private file names.
        self.assertEqual(classify("customer-acme-notes"), (None, "unrecognised:(no extension)"))

    def test_ignores_generated_and_vendored_code(self):
        for name, reason in [
                ("plc4net/tools/code-gen/src/generated/MSpecParser.cs", "generated"),
                ("app/Foo.Designer.cs", "generated"), ("api/user_pb2.py", "generated"),
                ("static/app.min.js", "generated"), ("build/out.js", "generated"),
                ("web/node_modules/x/index.js", "vendored"),
                ("third_party/lib/a.c", "vendored"),
                ("mailman-web/django-allauth-65.4.1/allauth/app.py", "vendored")]:
            with self.subTest(name):
                self.assertEqual(classify(name), (None, reason))

    def test_generated_header_only_counts_at_the_top_of_a_file(self):
        top = "@@ -0,0 +1,3 @@\n+// <auto-generated>\n+// do not edit\n+class A {}"
        middle = "@@ -10,3 +12,4 @@\n+// generated by hand last week\n+class A {}"
        plain = "@@ -0,0 +1,2 @@\n+using System;\n+class A {}"
        self.assertEqual(classify("A.cs", top), (None, "generated"))
        self.assertEqual(classify("A.cs", middle), ("C#", ""))
        self.assertEqual(classify("A.cs", plain), ("C#", ""))
        self.assertEqual(classify("A.cs", None), ("C#", ""))


class CollectionTests(unittest.TestCase):
    def test_only_the_users_non_merge_non_root_commits_are_listed(self):
        client = FakeClient({"o/r": [commit("own"), commit("other", "SomeoneElse"),
                                     commit("merge", parents=2), commit("root", parents=0),
                                     commit("unlinked", author=None),
                                     commit("mixed-case", author="tomnewchao")]})
        self.assertEqual(list_commits(client, "o/r", USER, SINCE, NOW), ["own", "mixed-case"])
        self.assertEqual(client.params, {"author": USER, "per_page": 100,
                                         "since": "2025-10-08T00:00:00Z",
                                         "until": "2026-10-08T00:00:00Z"})

    def test_whole_file_deletions_generated_and_non_code_are_not_counted(self):
        client = FakeClient(details={("o/r", "abc"): [[
            changed("src/a.go", 4, 1),
            changed("old/Driver.cs", 0, 500, status="removed"),
            changed("README.md", 100),
            changed("gen/generated/x.cs", 300, status="added"),
            changed("src/b.py", 2, 3, status="renamed"),
            changed("src/empty.py", 0, 0)]]})
        changes, ignored, counted = commit_changes(client, "o/r", "abc")
        self.assertEqual(dict(changes), {"Go": 5, "Python": 5})
        self.assertEqual(dict(ignored), {"removed-file": 500, "non-code": 100, "generated": 300})
        self.assertEqual(sorted(counted), [(5, "src/a.go"), (5, "src/b.py")])

    def test_file_lists_are_read_across_pages_and_summed_across_commits(self):
        client = FakeClient(
            {"o/r": [commit("c1"), commit("c2")]},
            {("o/r", "c1"): [[changed("a.go", 1)], [changed("b.go", 2)]],
             ("o/r", "c2"): [[changed("c.py", 4, 1)]]})
        result = repo_changes(client, "o/r", USER, SINCE, NOW)
        self.assertEqual(result["languages"], {"Go": 3, "Python": 5})
        self.assertEqual(result["commits"], 2)

    def test_a_possibly_truncated_file_list_is_an_error(self):
        files = [changed(f"f{i}.py", 1) for i in range(3000)]
        client = FakeClient(details={("o/r", "big"): [files]})
        with self.assertRaises(GitHubError):
            commit_changes(client, "o/r", "big")


class TransformTests(unittest.TestCase):
    def stats(self):
        def repo(name, stars=0, forks=0, views=0, lines=999, private=False, langs=None):
            return {"name": name, "stars": stars, "forks": forks, "views": views,
                    "lines_changed": lines, "private": private,
                    "languages": langs or [{"name": "Go", "size": 10 ** 7, "color": "#00ADD8"}]}
        return {"user": USER, "repo_contributions": 90, "issue_contributions": 133,
                "commit_contributions": 2862, "pr_contributions": 1353,
                "review_contributions": 18, "emails": ["me@example.com"],
                "repositories": [
                    repo("openIndu/active", stars=3, forks=1, views=7),
                    repo("openIndu/idle", stars=5, forks=2, views=9),
                    repo("apache/plc4x", stars=1754, forks=509, views=40,
                         langs=[{"name": "Java", "size": 10 ** 8, "color": "#b07219"}]),
                    repo("TomNewChao/forked", stars=0),
                    repo("secret/private-app", private=True)]}

    def client(self):
        detail = lambda files: [files]
        return FakeClient(
            {"openIndu/active": [commit("a1")], "apache/plc4x": [commit("p1")],
             "secret/private-app": [commit("s1")]},
            {("openIndu/active", "a1"): detail([changed("x.cs", 3), changed("y.py", 7)]),
             ("apache/plc4x", "p1"): detail([changed("plc4net/Foo.cs", 20),
                                            changed("plc4net/old.cs", 0, 900, status="removed")]),
             ("secret/private-app", "s1"): detail([changed("app.ts", 5)])})

    def run_transform(self, client=None, log=None, **kwargs):
        log = log if log is not None else []
        result = transform(self.stats(), client or self.client(), SINCE, NOW,
                           excluded=["TomNewChao/forked"], log=log.append, **kwargs)
        return result, log

    def test_languages_and_lines_become_the_users_recent_changes(self):
        (stats, commits, _), _ = self.run_transform()
        by_name = {repo["name"]: repo for repo in stats["repositories"]}
        active = by_name["openIndu/active"]
        self.assertEqual(active["languages"], [{"name": "Python", "size": 7, "color": "#3572A5"},
                                               {"name": "C#", "size": 3, "color": "#178600"}])
        self.assertEqual(active["lines_changed"], 10)
        self.assertEqual(by_name["apache/plc4x"]["languages"],
                         [{"name": "C#", "size": 20, "color": "#178600"}])
        self.assertEqual(by_name["apache/plc4x"]["lines_changed"], 20)
        self.assertEqual(commits, 3)

    def test_inactive_repos_stay_listed_with_nothing_counted(self):
        (stats, _, _), _ = self.run_transform()
        idle = {repo["name"]: repo for repo in stats["repositories"]}["openIndu/idle"]
        self.assertEqual(idle["languages"], [])
        self.assertEqual(idle["lines_changed"], 0)
        self.assertEqual((idle["stars"], idle["forks"], idle["views"]), (5, 2, 9))

    def test_upstream_popularity_is_not_counted_as_the_users_own(self):
        (stats, _, _), _ = self.run_transform()
        by_name = {repo["name"]: repo for repo in stats["repositories"]}
        plc4x = by_name["apache/plc4x"]
        self.assertEqual((plc4x["stars"], plc4x["forks"], plc4x["views"]), (0, 0, 0))
        active = by_name["openIndu/active"]
        self.assertEqual((active["stars"], active["forks"], active["views"]), (3, 1, 7))

    def test_everything_else_in_the_file_is_untouched(self):
        original = self.stats()
        (stats, _, _), _ = self.run_transform()
        for key in ("repo_contributions", "issue_contributions", "commit_contributions",
                    "pr_contributions", "review_contributions", "emails", "user"):
            self.assertEqual(stats[key], original[key])
        self.assertEqual([repo["name"] for repo in stats["repositories"]],
                         [repo["name"] for repo in original["repositories"]])

    def test_excluded_repos_are_neither_queried_nor_changed(self):
        client = self.client()
        (stats, _, _), _ = self.run_transform(client)
        self.assertNotIn("TomNewChao/forked", client.repos_asked)
        forked = {repo["name"]: repo for repo in stats["repositories"]}["TomNewChao/forked"]
        self.assertEqual(forked["lines_changed"], 999)
        self.assertEqual(forked["languages"][0]["name"], "Go")

    def test_documentation_only_work_counts_for_nothing(self):
        client = FakeClient({"openIndu/active": [commit("d1")]},
                            {("openIndu/active", "d1"): [[changed("README.md", 40)]]})
        (stats, _, ignored), _ = self.run_transform(client)
        active = {repo["name"]: repo for repo in stats["repositories"]}["openIndu/active"]
        self.assertEqual((active["languages"], active["lines_changed"]), ([], 0))
        self.assertEqual(ignored["non-code"], 40)

    def test_private_repository_names_never_reach_the_log(self):
        _, log = self.run_transform()
        text = "\n".join(log)
        self.assertNotIn("secret/private-app", text)
        self.assertIn(display_name({"name": "secret/private-app", "private": True}), text)
        self.assertIn("openIndu/active: 1 commits, 10 lines", text)

    def test_api_failure_names_a_private_repo_only_by_hash(self):
        client = FakeClient(fail={"secret/private-app"})
        with self.assertRaises(GitHubError) as raised:
            self.run_transform(client)
        message = str(raised.exception)
        self.assertNotIn("private-app", message)
        self.assertIn("<private:", message)
        self.assertIn("HTTP 404", message)


class RetryTests(unittest.TestCase):
    def test_retry_delay(self):
        now = lambda: 1000
        self.assertEqual(retry_delay(502, {}, "", 2), 4)
        self.assertEqual(retry_delay(503, {}, "", 10), 60)
        self.assertEqual(retry_delay(403, {"Retry-After": "7"}, "", 1), 7)
        self.assertEqual(retry_delay(403, {"X-RateLimit-Remaining": "0",
                                           "X-RateLimit-Reset": "1090"}, "", 1, now), 91)
        self.assertEqual(retry_delay(429, {}, "You have exceeded a secondary rate limit", 2), 60)
        self.assertIsNone(retry_delay(403, {}, "Resource not accessible by personal access token", 1))
        self.assertIsNone(retry_delay(404, {}, "", 1))
        self.assertIsNone(retry_delay(403, {"Retry-After": "99999"}, "", 1))
        self.assertIsNone(retry_delay(403, {"X-RateLimit-Remaining": "0",
                                            "X-RateLimit-Reset": "999999"}, "", 1, now))

    def client(self, steps):
        sleeps = []

        def opener(request, timeout):
            self.assertEqual(request.get_header("Authorization"), "Bearer secret-token")
            step = steps.pop(0)
            if isinstance(step, Exception):
                raise step
            return step
        return GitHubClient("secret-token", opener=opener, sleep=sleeps.append), sleeps

    def test_transient_errors_are_retried(self):
        client, sleeps = self.client([http_error(502), OSError("reset"), FakeResponse([1])])
        self.assertEqual(list(client.pages("/x")), [[1]])
        self.assertEqual(sleeps, [2, 4])

    def test_permanent_errors_fail_at_once_without_leaking_the_token(self):
        client, sleeps = self.client([http_error(404)])
        with self.assertRaises(GitHubError) as raised:
            list(client.pages("/repos/o/r/commits"))
        self.assertEqual(str(raised.exception), "HTTP 404")
        self.assertEqual(sleeps, [])

    def test_gives_up_after_five_attempts(self):
        client, sleeps = self.client([http_error(502) for _ in range(5)])
        with self.assertRaises(GitHubError):
            list(client.pages("/x"))
        self.assertEqual(len(sleeps), 4)

    def test_pagination_follows_link_headers_and_empty_repos_yield_nothing(self):
        client, _ = self.client([
            FakeResponse([1], '<https://api.github.com/x?page=2>; rel="next", '
                              '<https://api.github.com/x?page=9>; rel="last"'),
            FakeResponse([2])])
        self.assertEqual(list(client.pages("/x", {"per_page": 1})), [[1], [2]])
        empty, _ = self.client([http_error(409)])
        self.assertEqual(list(empty.pages("/repos/o/r/commits")), [])

    def test_a_token_is_required(self):
        with self.assertRaises(ValueError):
            GitHubClient("")


class CommandLineTests(unittest.TestCase):
    def test_main_writes_the_rewritten_json_and_a_clean_log(self):
        stats = {"user": USER, "emails": [], "repo_contributions": 1,
                 "repositories": [
                     {"name": "secret/private-app", "stars": 0, "forks": 0, "views": 0,
                      "lines_changed": 5, "private": True,
                      "languages": [{"name": "Go", "size": 99, "color": None}]}]}
        client = FakeClient({"secret/private-app": [commit("s1")]},
                            {("secret/private-app", "s1"): [[changed("app.ts", 5)]]})
        with tempfile.TemporaryDirectory() as folder:
            source, target = os.path.join(folder, "in.json"), os.path.join(folder, "out.json")
            with open(source, "w", encoding="utf-8") as handle:
                json.dump(stats, handle)
            output = io.StringIO()
            with mock.patch.object(recent_stats, "GitHubClient", return_value=client), \
                    mock.patch.dict(os.environ, {"GH_TOKEN": "secret-token"}), \
                    contextlib.redirect_stdout(output):
                recent_stats.main(["--input", source, "--output", target, "--days", "30"])
            with open(target, encoding="utf-8") as handle:
                result = json.load(handle)
        self.assertEqual(result["repositories"][0]["languages"],
                         [{"name": "TypeScript", "size": 5, "color": "#3178c6"}])
        self.assertEqual(result["repositories"][0]["lines_changed"], 5)
        self.assertNotIn("private-app", output.getvalue())
        self.assertNotIn("secret-token", output.getvalue())
        self.assertIn("TypeScript: 5 (100.0%)", output.getvalue())

    def test_a_non_positive_window_is_rejected(self):
        with contextlib.redirect_stderr(io.StringIO()), self.assertRaises(SystemExit):
            recent_stats.main(["--days", "0"])


if __name__ == "__main__":
    unittest.main()
